### PR TITLE
Use psframework for PasswordState-Management Module

### PR DESCRIPTION
**Pull request by trir262**
This PR will modify the project so it is easier to create pester tests, update documentation and use strings for messages.
A first batch of unit tests have been added as well

Fixes: #81 
References: #58

### CODE REVIEW

**Comment by trir262** [comment]
@dnewsholme I have created a pull request so the unit tests are already part of your repo.

**Comment by trir262** [comment]
I'll continue creating tests, but are you able to generate some test json's for passwordhost? Because my environment does not allow querying for those.

**Comment by dnewsholme** [comment]
I'll see if i can export some password hosts for you might be a couple of days before i can do it though as i've not got much spare time at the moment.

**Comment by dnewsholme** [comment]
I've had to revert the head of master as this pull request broke a number of things. We'll need to reopen at and ill run some tests from your branch.

I'd like to integrate what you've done but the Get and set passwordstateenvironment were no longer working. The loading of the class stopped working and the loading of the private functions on the built version. Potentially it's just the build process needs changing.

**Comment by trir262** [comment]
Sorry to hear that. Can you create issues with the errors you receive so I can resolve it? I'll resolve my own defects then

**Comment by dnewsholme** [comment]
@trir262  I've had a bit of time to look at this today. It looks like everything you did worked. 

However the problem is the build process which packages the module didn't include all your new files which are needed and the psd1 file for the module doesn't have PSFramework as module dependency so it never installs alongside the passwordstate module.

**Comment by dnewsholme** [comment]
I'm going to merge your changes into my dev branch and i'll fix the build process up before merging back into master.

**Comment by dnewsholme** [comment]
@trir262  finally got some time to fix up the build process. I've merged all your work in, thanks a bunch for your contributions it's actually awesome. We're now ready for any further pull requests you may have.

**Pull request merged**
