### PR TITLE
Minor - *-PasswordStateHost

### PR DESCRIPTION
**Pull request by colombeen**
New functions to interact with hosts in the PasswordState system

Missing:
* Pester test

### CODE REVIEW

**Comment by colombeen** [comment]
Added Remove-PasswordStateHost (but will need testing)

**Comment by dnewsholme** [comment]
These look good to me. All builds are failing atm as i've exceeded my Azure Credit but ill get it sorted.

**Comment by colombeen** [comment]
Added New-PasswordStateHost (but will need testing)

**Comment by dnewsholme** [comment]
Thanks for the contribution, the management of hosts was on my radar as something to do in the future.

I've sorted the tests they'll run again now. 

Your cmdlets are failing a the PSScriptAnalzyer tests due to whitespace.

Do the following to auto remove the whitespace:

```powershell
install-module PSScriptAnalyzer
$files = get-childitem .\Functions\*.ps1 -recurse | Where-Object {$_.fullname -notlike "*.Tests*"}
$files | ForEach-Object {Invoke-ScriptAnalyzer -Path $_.FullName -fix}
```

Could do with getting some tests in for them as well. I'll give them a test and try and write some pester tests for them.

**Comment by colombeen** [comment]
I should have added the addition of the new functions to the changelog

**Comment by dnewsholme** [comment]
No problem I'll push a no build version and update the changelog.

**Comment by colombeen** [comment]
I've been testing the new functions for a bit, seems that you can create multiple items with the same hostname, but when you want to delete them, that's an issue...

Removal uses the HostName, and not the ID, and with multiple results it just throws some crap about not being found.

=> API bug

**Comment by dnewsholme** [comment]
Yeah its weird how that part of the API behaves differently to the rest where the ID is used for deletes. Should raise with ClickStudios.

**Comment by colombeen** [comment]
[I've reported the issue](https://www.clickstudios.com.au/community/index.php?/topic/2724-passwordstate-api-delete-host-using-the-hostname-errors-out/)
They turned it into a feature request

**Comment by dnewsholme** [comment]
That's an odd response. It's quite clearly a bug.

**Pull request merged**
