### PR TITLE
Major - Get-PasswordStateFolder

### PR DESCRIPTION
**Pull request by colombeen**
Changed the way to search for folders with all possible properties that are provided by the API

### CODE REVIEW

**Comment by colombeen** [comment]
Tried to adjust the test file, not sure if it's enough

**Comment by dnewsholme** [comment]
Changes look good. Thanks again.

**Comment by colombeen** [comment]
> Changes look good. Thanks again.

Thanks :)

**Comment by dnewsholme** [comment]
Build completed for 2.1.0

**Pull request merged**
