### PR TITLE
Update PasswordResult Class for compatibility with PasswordState v9

### PR DESCRIPTION
**Pull request by eizedev**
Hi @dnewsholme 

In PasswordState v9 the `passwords` api method will return two new fields (GenericFieldInfo and OTP) that are currently not referenced in the `PasswordResult` class. So the retrieval of Passwords after updating to v9 are not possible.

I have included these to properties to the class (Type Array), now it is working again. This should not break compatibility with older version of passwordstate.

Reference OTP + GenericFieldInfo: #132

### CODE REVIEW

**Comment by eizedev** [comment]
@dnewsholme 

Your appveyor pipelines files because the pester module will be updated to v5: https://ci.appveyor.com/project/dnewsholme/passwordstate-management/builds/38111737

I think you should install Pester with the latest v4 version (`Install-Module -Name Pester -RequiredVersion 4.10.1`) in the pipeline until the code ist changed to v5.

**Comment by dnewsholme** [comment]
@eizedev  i've updated master with a new appveyor.yml which will install pester 4.10.1 if you pull that down your build should work again.

**Comment by eizedev** [comment]
@dnewsholme Thanks! Build succeeded :)

**Comment by dnewsholme** [comment]
Thanks for the contribution again @eizedev  :)

**Pull request merged**
