### PR TITLE
Added Switch for Passwordlists in Advanced Folders

### PR DESCRIPTION
**Pull request by herobrauni**
This "fixes" #155 . I'm  sure there is a better way, but for my use case this seems to do the trick.

### CODE REVIEW

**Review by eizedev — APPROVED** [review]
Fits for me. As a logical check it looks good and is also functional. Unfortunately, Get-PasswordstateFoder (or the actual API) does not provide a way to check the PermissionModel of a folder. I will add the switch in the Markdown documentation later on.

**Review by dnewsholme — APPROVED** [review]
Looks good to me.

**Comment by dnewsholme** [comment]
@herobrauni The PSScriptanalyzer tests are failing due to trailing whitespace on line 61. Any chance you could remove the whitespace?

Thanks

**Comment by herobrauni** [comment]
> @herobrauni The PSScriptanalyzer tests are failing due to trailing whitespace on line 61. Any chance you could remove the whitespace?
> 
> Thanks

Sure, done.

**Comment by dnewsholme** [comment]
Released in 4.4.45

**Pull request merged**
