### PR TITLE
Major - Get-PasswordStateList

### PR DESCRIPTION
**Pull request by colombeen**
Changed the way to search for password lists with all possible properties that are provided by the API

### CODE REVIEW

**Comment by colombeen** [comment]
I don't have any experience with the pester tests, would you be willing to change the test file?

**Comment by colombeen** [comment]
I'll try to check all functions to see if there are properties missing that could help the module become a more complete solution :-)

**Comment by colombeen** [comment]
Have you tested the new version? for some reason the Description parameter isn't working here... but it doesn't seem to be an issue on our side... looks to me like an API issue (unless you aren't receiving any issues while looking with the description param)

**Comment by dnewsholme** [comment]
Yeah I get a 500 error when passing anything other than an empty string as
a description. Definitely an API bug.

**Comment by colombeen** [comment]
noticed the same issue with another function but can't remember which one

**Pull request merged**
