### PR TITLE
Added new functions for running passwordstate reports, setting/getting permissions and rewrite of New-PasswordStatePassword

### PR DESCRIPTION
**Pull request by eizedev**
### Added

- [Invoke-PasswordStateReport](https://github.com/dnewsholme/PasswordState-Management/commit/13e3be88ce3b16496b13c0b18c1480b7463da247)
  - With this function it is now possible to run PasswordState reports through the API. See [documentation in the docs folder](docs/Invoke-PasswordStateReport.md) for more information.
- [Get-PasswordStatePermission](https://github.com/dnewsholme/PasswordState-Management/commit/30eb935a99360a90bda73631866ee54a05beb247)
  - Get passwordstate permissions through the api. See [documentation in the docs folder](docs/Get-PasswordStatePermission.md) for more information
- [New-PasswordStateFolderPermission](https://github.com/dnewsholme/PasswordState-Management/commit/13cb283d91e66f50e0c643828971ab4442925f56)
  - Grant permissions on passwordstate folders through the api. Check the [documentation in the docs folder](docs/New-PasswordStateFolderPermission.md) for more information.
- [New-PasswordStateListPermission](https://github.com/dnewsholme/PasswordState-Management/commit/75e3e3208c4fd989781d4533c8970bcfd393379a)
  - Grant permissions on passwordstate lists through the api. Check the [documentation in the docs folder](docs/New-PasswordStateListPermission.md) for more information.
- [New-PasswordStatePasswordPermission](https://github.com/dnewsholme/PasswordState-Management/commit/e737b593b9a3d4bef6830cef359ec832007e7fce)
  - Grant permissions on passwordstate passwords through the api. Check the [documentation in the docs folder](docs/New-PasswordStatePasswordPermission.md) for more information.
- [New-PasswordStateADSecurityGroup](https://github.com/dnewsholme/PasswordState-Management/commit/1ad88c1346152aa4300d2eb66bea74dc3dd5228c)
  -  Adds the possibility to create (import) an Active Directory Security Group in PasswordState. 
  - Check the [documentation in the docs folder](docs/New-PasswordStateADSecurityGroup.md) for more information.

### Changed

- [New-PasswordStatePassword](https://github.com/dnewsholme/PasswordState-Management/commit/1cf5334f8093f5518442873e0f704a72ba7e9094)
  -  Rewrite of `New-PasswordStatePassword`
    - All available API options are now integrated into this function.
    - PasswordReset, PasswordHeartbeat, Expirydays and date, Browser Extension fields, AllowExport, etc. 
    - Fixed bug that the genericfields would be added twice.
    - Added possibility to skip the existence check if a identical password entry was found.
  - Check the [documentation in the docs folder](docs/New-PasswordStatePassword.md) for more information.

### CODE REVIEW

**Comment by eizedev** [comment]
I am currently looking for the problem in the documentation with the [Nullable[System.Int32]] parameter types. It does not recognize it correctly.

**Comment by eizedev** [comment]
> Looks good. Some issues with the tests and parameters by the looks of it though?
> 
> Isn't [int32] nullable anyway and [Nullable[System.Int32]] is just longform for the same thing?

The long form is `System.Nullable`1[System.Int32]`, the short form `[Nullable[System.Int32]]` or `[Nullable[Int32]]`. I don't know at the moment why it is not correctly recognized by platyPS. 
I am using `[Nullable[System.Int32][]]` in another parameter and this is correctly identified by `Nullable`1[]`

**Comment by dnewsholme** [comment]
@eizedev I see, you're obviously know more about it than me. I suppose you could use the array even if it was for only 1 item?  `[Nullable[System.Int32][]]` 

Doesn't really fix the problem but works around it.

**Comment by eizedev** [comment]
> @eizedev I see, you're obviously know more about it than me. I suppose you could use the array even if it was for only 1 item? `[Nullable[System.Int32][]]`
> 
> Doesn't really fix the problem but works around it.

I tried that already, but it does not work. I also deleted the affected markdown help files and generated new files with `New-MarkdownHelp`, same problem.

Do you know why @trir262 removed the markdown help files for the internal functions with the last commit? https://github.com/dnewsholme/PasswordState-Management/commit/c09ce37be4ca5fc5de2b24ca439307ed5cab7675#diff-e3e2a9bfd88566b05001b02a3f51d286
I just executed `New-MarkdownHelp -Module passwordstate-management -OutputFolder .\docs\` and realized the newly generated markdown documentation.

**Comment by trir262** [comment]
The documentation for internal functions do not need to be part of the complete external help xml. That is why I removed them.

Regards,

**Comment by eizedev** [comment]
@trir262 ah, ok, then i will not try to upload these files again :-)

**Comment by eizedev** [comment]
@dnewsholme Found a workaround, all checks passed.

Now all `[Nullable[System.Int32][]]` are defined as an array (needed to regenerate the whole markdown file instead of updating it, don't know why).

**Comment by dnewsholme** [comment]
Nice. Glad you found a way round it and thanks for the pull request :)

**Pull request merged**
