### PR TITLE
#96 Improved, Changed, Added functions and documentation (see comment details)

### PR DESCRIPTION
**Pull request by eizedev**
As mentioned in #96 here is the pull request

### Added
  - Added new function for creating password dependencies
    - [New-PasswordStateDependency.ps1](https://github.com/eizedev/PasswordState-Management/blob/master/functions/New-PasswordStateDependency.ps1)
    - Including doc: [New-PasswordStateDependency.md](https://github.com/eizedev/PasswordState-Management/blob/master/docs/New-PasswordStateDependency.md)
  - Added possibility to sort the response/returned object by applying `-Sort`
    - This is also integrated to sort the `body` for verbose output
    - For this, added a function [Get-PSCustomObject](https://github.com/eizedev/PasswordState-Management/blob/master/internal/functions/Get-PSCustomObject.ps1) to sort existing PSCustomObjects
    - `$output | Get-PSCustomObject -Sort`
    - This is by default integrated in [New-PasswordStateResource.ps1 and Get-PasswordStateResource.ps1](https://github.com/eizedev/PasswordState-Management/commit/cfe1240986dc590bb6e40f4c284566c65d6c7006#diff-6c580cf902a9e40eb7eb1015127134f0)
  - Added [aliases](https://github.com/dnewsholme/PasswordState-Management/commit/61e17bcba780371eab0f31d7ab0242076ecc41e3) `Find-PasswordstateList` and `Find-PasswordStateFolder`
  - Added the documentation for `Get-PSCustomObject`

### Changed

  - Changed [New-PasswordStateFolder.ps1](https://github.com/eizedev/PasswordState-Management/blob/master/functions/New-PasswordStateFolder.ps1)
    - Removed:
      - `CopySettingsFromPasswordListID` does not exist for folders, removing it (it only exists on password lists).
  - Added:
    - Added the following new possible fields/options for creating folders through the api:
    ```
    CopyPermissionsFromPasswordListID
    CopyPermissionsFromTemplateID
    Guide
    PropagatePermissions
    ```
    - Also added API Key to body if authenticated only with the api key (this is best practise of ClickStudios)
  - Changed
    - Including doc: [New-PasswordStateFolder.md](https://github.com/eizedev/PasswordState-Management/blob/master/docs/New-PasswordStateFolder.md)
  - Updated [New-PasswordStateList.ps1](https://github.com/eizedev/PasswordState-Management/blob/master/functions/New-PasswordStateList.ps1)
    - Support all documented and some (currently not working) undocumented properties
    ```powershell
    CopySettingsFromPasswordListID
    CopyPermissionsFromPasswordListID 
    CopySettingsFromTemplateID 
    CopyPermissionsFromTemplateID
    LinkToTemplate
    PrivatePasswordList
    ApplyPermissionsForUserID 
    ApplyPermissionsForSecurityGroupID 
    ApplyPermissionsForSecurityGroupName 
    Permission
    ImageFileName
    SiteID 
    Guide
    ```
    - For the "currently not working or undocumented" properties i have opened a ticket at ClickStudios
    - Including doc: [New-PasswordStateList.md](https://github.com/eizedev/PasswordState-Management/blob/master/docs/New-PasswordStateList.md)
  - Updated all Markdown Documentation files under `docs`, added doc for already existing functions,  removed documentation for no longer available functions
  - Added/Updated the [external help](https://github.com/eizedev/PasswordState-Management/tree/master/en-us) file using PlatyPS `New-ExternalHelp` in the `en-US` folder
  - Fixed `PreventAuditing` on [Get-PasswordStateList](https://github.com/eizedev/PasswordState-Management/commit/bb45686ba3ca3a8d55bb9e95f1e1df1eefba4939#diff-f43b978c186a666f368759c03f231e88) if only PasswordListID was specified (PreventAuditing is not possible then)
  - [Renamed](https://github.com/eizedev/PasswordState-Management/commit/2241cefbc67f7b2140bd67a01f179c5ae1f9645a) `Update-PasswordStatePassword` to `Set-PasswordStatePassword` to comply with the Microsoft Approved Verbs
    - Set [alias](https://github.com/eizedev/PasswordState-Management/commit/2241cefbc67f7b2140bd67a01f179c5ae1f9645a#diff-1daccb4cd2f5e243f3088c162191cdd9) `Update-PasswordStatePassword`

### CODE REVIEW

**Comment by dnewsholme** [comment]
Looks like Get-PSCustomObject.ps1 isn't set to UTF8 encoding which is failing the pester tests.

The rest looks fine though. You alright to fix that up and i'll merge it.

**Comment by eizedev** [comment]
@dnewsholme Aaah... UTF-8 with BOM, i had UTF-8 as encoding. I also added the documentation for `Get-PSCustomObject`. Also fixed the other errors for not using write-verbose, write-warning etc. 
The only error that still exists is the missing documentation for parameter `-Sort` in `Get-PasswordStateResource`. The help is working for me, i have also regenerated the external help file.
Currently, don't know why this error is happening.

**Comment by dnewsholme** [comment]
@eizedev It's because it's missing the parameter in the help comment block on the function at the top (i think).

Something like this should fix it.
``` powershell
.PARAMETER Sort
    A switch Parameter to sort the output object.
```

**Comment by eizedev** [comment]
@dnewsholme Aaah..  i fixed it with the latest commit. 
Now the build succeeded.

I didn't realize that [comment_based_help](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comment_based_help?view=powershell-7) is still used in the older functions, I had completely overlooked that. As soon as you create the markdown help pages and the external help file for the module with platyPS, you can remove the commet_based_help entries in the scripts. 
You already talked about this in Issue #58 .

**Comment by dnewsholme** [comment]
@eizedev Yeah there is still a few old bits to clear up and that's one of the things.

Thank you very much for your contribution. It should be published to the PS gallery within 20 mins or so.

**Comment by dnewsholme** [comment]
New build is up. Took a bit longer due to a couple of issues with the build box powershellget and package management versions.

**Pull request merged**
