### PR TITLE
Update New-RandomPassword.ps1

### PR DESCRIPTION
**Pull request by colombeen**
Add support for the Quantity parameter for all parts of the function.

### CODE REVIEW

**Comment by colombeen** [comment]
I'm still thinking about changing the params for the function and adding every possible setting to the function as is provided by the API.

**Comment by dnewsholme** [comment]
> I'm still thinking about changing the params for the function and adding every possible setting to the function as is provided by the API.

The current changes look good.

If you do want to implement all parameters as options be aware that the password generation will only work if all parameters are passed into the url query string the api won't let you just pass in a subset except for quantity. It's a strange implementation.

**Comment by colombeen** [comment]
> If you do want to implement all parameters as options be aware that the password generation will only work if all parameters are passed into the url query string the api won't let you just pass in a subset except for quantity. It's a strange implementation.

Good to know, wasn't clear in the documentation.

**Comment by colombeen** [comment]
Will be checking PSGallery for the new version, the current one doesn't allow me to use the quantity param with PolicyID

**Comment by dnewsholme** [comment]
Yeah I'll build and merge tomorrow morning. I'll update once I have.

**Comment by dnewsholme** [comment]
published in the gallery:

https://www.powershellgallery.com/packages/passwordstate-management/0.0.107

**Comment by colombeen** [comment]
> published in the gallery:
> 
> https://www.powershellgallery.com/packages/passwordstate-management/0.0.107

Just a suggestion... could you use [semantic versioning](https://semver.org/), because at this point the version number is very confusing to me.

**Comment by colombeen** [comment]
On the PSGallery website, when you filter for linux or mac, the module disappears. Guess this is some setting that needs to be changed somewhere?

**Pull request merged**
